### ISSUE TITLE
Feature Req: Pull values for Light Mode, Light Opening/Closing Level, Open/Close Delay, etc.

### ISSUE THREAD

**Issue by AnthonyBe** [williamschey/hassio-omlet-smartcoop-door#1]
First up, many thanks for making this integration and sharing it with the community!

I'm sure you have a list of things you are working on, but I just wanted to add a few things to it (if not already on it).

Is it possible to pull the current values for:

1. Autodoor Mode (i.e. Manual, Time, or Light)
2. Current Time
3. Light Opening Level (if Autodoor in Light Mode) in lx (or is it % given the values range from 0 to 100?)
4. Light Closing Level (if Autodoor in Light Mode) in lx (or is it % given the values range from 0 to 100?)
5. Opening Time (if Autodoor in Time Mode)
6. Closing Time (if Autodoor in Time Mode)
7. Door Opening Delay (in minutes)
8. Door Closing Delay (in minutes)
9. Door State Information (History tracking)
10. Door Error Information (History tracking)

**Comment by dpwood** [comment]
Hi Anthony,

Thanks for your input. The next release is a bit of an overhaul and introduces new features and entities, including some configuration controls.

We're only just getting started, but your list looks achievable and aligned with our own goals. In fact, some of it is already in the next release and the rest shouldn't be far behind - check out the dev branch if you'd like a sneak peek.

Kind Regards,
Dave

**Comment by AnthonyBe** [comment]
Thanks Dave!!
