### ISSUE TITLE
Door Light Issue

### ISSUE THREAD

**Issue by Tillsy** [williamschey/hassio-omlet-smartcoop-door#2]
G'day guys

With dpwood's version of the integration he fixed the following two bugs for me regarding the coop light:

1. Not turning on
2. Toggling itself back off again in the interface

I have swapped over to this integration since he has discontinued that one, and these two bugs are back again.

After a fair bit of playing around the issue is related to #2 - the integration is immediately toggling off again, even though there is a delayed "request" submitted to Omelet's cloud for the light... so if you play with the toggle again in the meantime things go haywire, if you leave it off it becomes on later.  Very confusing and causes their API/the device to get into a stuck state requiring a power cycle.

dpwood already fixed this in his version, hoping the toggle fix can be made in this one too :)

Thanks so much!

Cheers
Chris

**Comment by dpwood** [comment]
Hi Chris, good to hear from you. Glad you're with us.

My changes are in the dev branch, including those fixes. I believe this integration will work nicely with both your doors too.

It'll be going in to the main branch and a release very soon.

**Comment by Tillsy** [comment]
> Hi Chris, good to hear from you. Glad you're with us.
> 
> My changes are in the dev branch, including those fixes. I believe this integration will work nicely with both your doors too.
> 
> It'll be going in to the main branch and a release very soon.

Thanks mate, and sure is both door lit up even better than before when I switched over.  Naming is a bit funny (I think my nest door is called nest_door_nest_door_nest_door_door but it works and is tied into my whole system now (eg reacts to my weather station on roof to factor true light levels, movement inside the coop, etc.

Thanks so much for all the work you guys have poured in, and our mysterious honour who wrote the original core code and then vanished 🤷‍♂️

**Comment by dpwood** [comment]
Yup, the double naming is also fixed in the dev branch. 

The entity ids won't automatically rewrite when you install the update, but if you re-add it, the new entity ids, with the new version, are a lot cleaner.
