### ISSUE TITLE
Wrong Status Colour

### ISSUE THREAD

**Issue by Tillsy** [williamschey/hassio-omlet-smartcoop-door#3]
G'day guys

This is a bit of an odd one but may also make perfect sense!

When a door or window is open, lights on, etc in HA the status is lit "yellow".

However with this integration when my coop or nest doors (I have two AutoDoors) are open they light up... purple?

Sample below:
<img width="433" alt="image" src="https://github.com/user-attachments/assets/e3734f4f-6708-4a62-802d-eecf0c023837" />

Hope this makes sense ;)
Cheers
Chris

**Comment by AnthonyBe** [comment]
I noticed that as well :)
![msedge_2024-12-14_17-12-34](https://github.com/user-attachments/assets/5781892c-4fe6-4144-8c68-ef0e4dac8966)

I assume there is a way to define default colours for different statuses within the integration (e.g. open = green, closed = red)? Or is this something that HA does globally?

**Comment by AnthonyBe** [comment]
Oh, side note, @Tillsy, where/how did you get the Chicken icon?

**Comment by dpwood** [comment]
> Oh, side note, @Tillsy, where/how did you get the Chicken icon? Critical update for my Dashboard required!

I second this

**Comment by Tillsy** [comment]
> Oh, side note, @Tillsy, where/how did you get the Chicken icon? Critical update for my Dashboard required!

There is an integration called "Custom Brand Icons" that adds additional Material Design Icons (the format used by HA) for custom brands and branded devices... say a PlayStation, or an LG washing machine, or Philips Hue devices, Tesla logo, and things like that.  Very specific items you may want to integrate and identify above and beyond the regular generic icons.

I've kindly asked them to create a few specific things such as a picture of a Tesla car itself, a seat heating icon, a chicken, and yes even eggs (for my nest door) and a chicken coop (for the coop door).  They are super accomodating and enabled me to customise my kitchen dashboard quite a bit:

![image](https://github.com/user-attachments/assets/92c5522a-b91c-4c1a-85d5-e74589751f96)

**Comment by dpwood** [comment]
We also need to hear about your egg counter please!!

On the topic of the icon colours though, it looks like this is standard behaviour for a door (a cover). The colour selection is based on this order:

![image](https://github.com/user-attachments/assets/8adae09d-8966-4fdd-8df8-3363dcd5c9c7)

**state-cover-door-open-color** and **state-cover-open-color** aren't defined by default (you can define them in your own themes), **state-cover-active-color** however is purple by default, thanks to [this line](https://github.com/home-assistant/frontend/blob/0c7d689b5a68d5a66bdd85dbc70b74689cc6b2a7/src/resources/ha-style.ts#L156) in the HA front end code.

So it's not something we as the component writers can really control, but you can override it with a theme:

```
frontend:
  themes:
    my_theme:
      state-cover-active-color: "var(--state-active-color)"
```

Closed, by the way, is the following order:

![image](https://github.com/user-attachments/assets/5d0583ba-d70e-4f96-a395-4ce4e9d1c8af)

Closing and Opening have their own states. Credit to HA, It's very flexible.

I think this closes the issue but I'm not done hearing about that egg counter.

**Comment by Tillsy** [comment]
Ah yes I did notice they were considered a "cover" - coolio overriding that fixed it:
<img width="383" alt="image" src="https://github.com/user-attachments/assets/ff991806-2e26-4b43-8ae9-efda0c8dfb08" />

I have cameras inside my coop for movement detection, sanity, and yes egg checking - I've done (extensive) object detection training to have it lock onto the eggs.  This way when I get home I get a greeting ala Back To The Future 2 "Welcome home ~~Marty~~ Chris.  There is a delivery in the letterbox.  There are x eggs to collect." that sort of thing, plus adhoc announcements as those things occur while we are home.

Of all my home automation, to be honest my absolute favourite is that when I detect a delivery I take a snapshot using my driveway camera.  This way when our dashboard is flashing that there is a package in the mailbox I tap the icon and see a picture of when the delivery taking place - enabling us to know if it was merely someone putting junk mail in there or an actual package being delivered.  Super handy - plus second from that I put a light inside the mailbox and when we open it I trigger the light on/off so we can see in there at night (these days with third party non-couriers doing deliveries, ala Amazon uber style deliveries, they sometimes come in the evening).

**Comment by dpwood** [comment]
> Ah yes I did notice they were considered a "cover" - coolio overriding that fixed it: <img alt="image" width="383" src="https://private-user-images.githubusercontent.com/103569790/395762690-ff991806-2e26-4b43-8ae9-efda0c8dfb08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxNjQwMTYsIm5iZiI6MTczNDE2MzcxNiwicGF0aCI6Ii8xMDM1Njk3OTAvMzk1NzYyNjkwLWZmOTkxODA2LTJlMjYtNGI0My04YWU5LWVmZGEwYzhkZmIwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQwODA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2RlYzJlYzY2OTJhYjI0MzgyN2RhMDkzZjUzMjY0OGM0YTViNWVkMzdiMDljNDMzMDA4NGU1MTAwMjEwZWJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D509HuqTINSnGDHDzIRcXC22bxcMA-kKPyCZ5YMQjrE">
> 
> I have cameras inside my coop for movement detection, sanity, and yes egg checking - I've done (extensive) object detection training to have it lock onto the eggs. This way when I get home I get a greeting ala Back To The Future 2 "Welcome home ~Marty~ Chris. There is a delivery in the letterbox. There are x eggs to collect." that sort of thing, plus adhoc announcements as those things occur while we are home.
> 
> Of all my home automation, to be honest my absolute favourite is that when I detect a delivery I take a snapshot using my driveway camera. This way when our dashboard is flashing that there is a package in the mailbox I tap the icon and see a picture of when the delivery taking place - enabling us to know if it was merely someone putting junk mail in there or an actual package being delivered. Super handy - plus second from that I put a light inside the mailbox and when we open it I trigger the light on/off so we can see in there at night (these days with third party non-couriers doing deliveries, ala Amazon uber style deliveries, they sometimes come in the evening).

Very cool! What are you using for object detection? Frigate or something more bespoke?

**Comment by AnthonyBe** [comment]
I'm also keen to understand the egg count object detection mechanism. 

I installed a Ring Camera in my coop nightbox recently for no other reason other than 'because I can'. As we got into summer here in Australia, and it being light later, I did have the occasional particularly light evening where my Omlet Autodoor closed before any chooks had time to bed. The camera became an easy way for me to check from the comfort of the couch whether everyone had made it in. On the odd occasion there were some missing, I could remotely open the door, and usually within a few minutes, the stragglers would go to bed and I could then re-close the Omlet Autodoor.

**Comment by dpwood** [comment]
I have a ring camera in there for the same reason, but still want something more automated.

I put little ankle tags on them all, only these have tiny 134.2kHz pet microchips in them. 

3D printed an insert that slips into that doorway wedge containing a scanning loop, ESP32 and lipo battery. It works a treat, but the scanner is too power hungry and only lasts a couple of days. I've got a low power presence detection sensor which activates the scanner only when a chicken is detected. Should last a lot longer but haven't figured out where to mount that yet so that it has a good view of the doorway and doesn't just get covered in chicken shit.😕

**Comment by Tillsy** [comment]
I use Frigate and some object training to count the eggs, more so to be aware there are eggs to collect at all but super handy to be told how many and also automatically track their laying patterns.

Albeit in my case I provide them artificial light early in the morning to ensure they have a consistent amount of light per day - this avoids the typical 26 hour laying cycle that means they lay later and later each day and then eventually skip a day, in my case my girls lay like clockwork every single day :)
