### ISSUE TITLE
Possible Feature Request or linked side project - Egg/Chicken image object detection

### ISSUE THREAD

**Issue by AnthonyBe** [williamschey/hassio-omlet-smartcoop-door#7]
I wanted to start a dedicated thread in case there was enough interest and viability in this topic.

I was really interested in @Tillsy description in this [other thread](https://github.com/williamschey/hassio-omlet-smartcoop-door/issues/3) of how he is using Frigate to do object detection and report how many eggs are sitting in the laying box/s.

I could see two really beneficial uses for this type of technology:

1. Egg counting
2. Chicken counting (e.g. how many chickens are visible? Are all my chickens (based on a programmed 'coop population' integer) in the coop now that the door is closed or do I have to go and manage some stragglers? Could we even delay/override the Omlet autodoor light triggered close if not all chickens are counted, and then close once we have the correct number?)

I also own cats and have investigated many smart cat doors on the market over the years. Some use ML/AI to keep track of how many cats are 'inside' so that you can delay time-based door locking if you have a straggler. I've also seen one that uses AI to detect if your cat has something in its mouth and keeps the door closed so your fur-baby doesn't bring you a 'present'. I can see a lot of ways that many of us could combine this Omlet integration with a bespoke system like Frigate to really make our coops smarter. Heck, I wouldn't be surprised if the folks at Omlet haven't considered an "Omlet camera" that complements the Omlet light, connects to the Omlet controller, and does a lot of what we're talking about here.

I can appreciate that Frigate is a separate Add-On with it's own integration and therefore the install part of that can be easily documented (their docs are pretty good from what I've tested), but where I'm hoping we can crowd-source to save time and energy is the training of the system in egg and chicken detection. This is where my knowledge hits a wall, but I know others here have done it and/or are way smarter than me and could do it it :)

Thoughts?

**Comment by dpwood** [comment]
Love the idea, I'm on board, but it's out of scope of this project until Omlet adopt it in a way we can integrate in to HA.

Omlet, I hope you're listening!

The microcontroller on the Smart Coop is an ESP32, manufactured by Espressif. Awesome little power-house of a chip. Espressif also provide a code library, called [ESP-WHO](https://github.com/espressif/esp-who), with examples for doing computer vision and object recognition using the ESP32.

There are loads of very cheap cameras that can be used for this job. The OV2640 is very popular and costs only a few bucks. 

An egg-detection, camera add-on would be just lovely!

**Comment by Tillsy** [comment]
G'day guys!

When I originally setup my egg counting I did try chicken counting too - you likely saw I have cameras in BOTH the nesting and sleeping areas.  The good news is Frigate's built in "bird" object happily recognises the chickens as birds.  The bad news is when they are huddled together they are just a big blob, so while you may or may not still see a "bird" Frigate can't individual identify and thus count them.  Early in the evening when say two or three of them go in and sit separately yes, but once they are all in or start huddling it doesn't work.

The alternative might be to tackle it the other way around - a camera outside the coop and if 1) Door is closed AND 2) Bird detected outside then re-open door, wait a few minutes, re-close door?

Just a thought?

**Comment by AnthonyBe** [comment]
> The bad news is when they are huddled together they are just a big blob, so while you may or may not still see a "bird" Frigate can't individual identify and thus count them. Early in the evening when say two or three of them go in and sit separately yes, but once they are all in or start huddling it doesn't work.

Yeah, that doesn't surprise me at all.  Even when I've had as few as 3 hens, when checking the camera feed we've thought we were missing a bird as they love to quite literally sit on top of each other sometimes!
 
> The alternative might be to tackle it the other way around - a camera outside the coop and if 1) Door is closed AND 2) Bird detected outside then re-open door, wait a few minutes, re-close door?
> 

Maybe. I guess it depends on how people have their coop and run setup and how their hens behave. It wouldn't work for me as usually when I have a hen miss 'curfew' and get locked out, they'll come and sit on, or under, a table on my back deck. Mine have rarely been as disciplined as to sit on the ladder/ramp outside the night box! But for others it might work perfectly.

**Comment by williamschey** [comment]
Great idea and might even work as a blueprint. Closing as it is outside the scope of this little integration.
