### ISSUE TITLE
Setting Open/Close time from HA

### ISSUE THREAD

**Issue by tinutac** [williamschey/hassio-omlet-smartcoop-door#8]
Hello guys, 

Thanks a lot for putting the effort in this integration!

I was wondering if setting the open/close time from HA is on your roadmap. 

My scenario: leave the Omlet on time based automatic open/close and update the open/close time based on the sunrise/sunset from HA. This way, even if the Omlet goes offline (due to a bad wifi connection) it would still close on time.

Tillsy already proposed an workaround but it would be nice(r) if that would simply be a feature on the integration. 

Thanks again!

**Comment by williamschey** [comment]
Hi @tinutac,

That should already be there and working. As of v0.9.2, it is in the configuration section.

![image](https://github.com/user-attachments/assets/eeb44b7b-d8d6-4031-beab-7b45cc9fb633)

Let me know if it doesn't work, feel free to open a new ticket with some info (like version etc.) and screenshots.

Cheers,
Will
